web_browser:
  type: 'chrome'
  headless: true
  no-sandbox: true
  window_width: 1200
  window_height: 800
  disable_images: false
  disable-dev-shm-usage: true
db:
  host: '185.253.219.150'
  port: '3306'
  name: 'insta'
  user: 'root'
  passwd: 'HblVQ$z*6efI'
insta_account:
  login: 'maxbardks43'
  password: '112233ale'