web_browser:
  type: 'chrome'
  headless: true
  window_width: 1324
  window_height: 960
  disable_images: false
db:
  host: '185.253.219.150'
  port: '3306'
  name: 'insta'
  user: 'root'
  passwd: 'HblVQ$z*6efI'
insta_account:
  login: 'maxbardks43'
  password: '112233ale'
